name = "edgessh"
main = "src/worker.ts"
compatibility_date = "2026-07-01"
workers_dev = true
preview_urls = false

routes = [
  { pattern = "ssh.404nofound.eu.org", custom_domain = true }
]

[build]
command = "npm run build:web"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[vars]
CONNECT_TIMEOUT_MS = "10000"

[[durable_objects.bindings]]
name = "SSH_SESSIONS"
class_name = "SSHSessionDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SSHSessionDO"]

[[d1_databases]]
binding = "DB"
database_name = "edgessh-accounts"
database_id = "e667cd8c-ac78-496d-b517-aa500bb17122"
migrations_dir = "migrations"
